CREATE TABLE USERS (
	UserID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(100) NOT NULL UNIQUE,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    UserRole ENUM('Customer', 'Seller', 'Administrator') NOT NULL,
    FirstName VARCHAR(100),
    LastName VARCHAR(100),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ADDRESSES (
	AddressID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    AddressType ENUM('Shipping', 'Billing') NOT NULL,
    StreetAddress VARCHAR(255) NOT NULL,
    City VARCHAR(100) NOT NULL,
    District VARCHAR(100),
    Neighborhood VARCHAR(100),
    ZipCode VARCHAR(20) NOT NULL,
    Country VARCHAR(100) NOT NULL,
    
    FOREIGN KEY (UserID) REFERENCES USERS(UserID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE CATEGORIES (
	CategoryID INT PRIMARY KEY AUTO_INCREMENT,
    CategoryName VARCHAR(100) NOT NULL UNIQUE,
    Description TEXT
);

CREATE TABLE CATALOGS (
	CatalogID INT PRIMARY KEY AUTO_INCREMENT,
    SellerID INT NOT NULL UNIQUE,
    CatalogName VARCHAR(255) NOT NULL,
    
    FOREIGN KEY (SellerID) REFERENCES USERS(UserID)
		ON DELETE RESTRICT
		ON UPDATE CASCADE
);

CREATE TABLE PRODUCTS (
	ProductID INT PRIMARY KEY AUTO_INCREMENT,
    CatalogID INT NOT NULL,
    CategoryID INT,
    ProductName VARCHAR(255) NOT NULL,
    Description TEXT,
    Price DECIMAL(10, 2) NOT NULL,
    StockQuantity INT NOT NULL,
    
    FOREIGN KEY (CatalogID) REFERENCES CATALOGS(CatalogID)
		ON DELETE RESTRICT
        ON UPDATE CASCADE,
    FOREIGN KEY (CategoryID) REFERENCES CATEGORIES(CategoryID)
		ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE TABLE ORDERS (
	OrderID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID INT NOT NULL,
    SellerID INT NOT NULL UNIQUE,
    ShippingAddressID INT NOT NULL,
    OrderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TotalAmount DECIMAL(10, 2) NOT NULL,
    OrderStatus ENUM('pending', 'processing', 'shipped', 'delivered', 'canceled') NOT NULL,
    
    FOREIGN KEY (CustomerID) REFERENCES USERS(UserID)
		ON DELETE RESTRICT
        ON UPDATE CASCADE,
    FOREIGN KEY (ShippingAddressID) REFERENCES ADDRESSES(AddressID)
		ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE ORDER_ITEMS (
	OrderItemID INT PRIMARY KEY AUTO_INCREMENT,
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL,
    PurchasePrice DECIMAL(10, 2) NOT NULL,
    
    FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES PRODUCTS(ProductID)
		ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE PAYMENTS (
	PaymentID INT PRIMARY KEY AUTO_INCREMENT,
    OrderID INT NOT NULL,
    PaymentDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Amount DECIMAL(10, 2) NOT NULL,
    PaymentMethod ENUM('credit card', 'transfer', 'wallet') NOT NULL,
    PaymentStatus ENUM('pending', 'completed', 'failed') NOT NULL,
    
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
        ON DELETE CASCADE
        ON UPDATE CASCADE 
);

CREATE TABLE SHIPMENTS (
	ShipmentID INT PRIMARY KEY AUTO_INCREMENT,
    OrderID INT NOT NULL UNIQUE,
    ShipmentDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TrackingNumber VARCHAR(255),
    ShipmentStatus ENUM('processing', 'shipped', 'in_transit', 'delivered'),
    
    FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE REVIEWS (
	ReviewID INT PRIMARY KEY AUTO_INCREMENT,
    OrderItemID INT NOT NULL,
    CustomerID INT NOT NULL,
    Rating INT NOT NULL,
    Comment TEXT,
    ReviewDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (OrderItemID) REFERENCES ORDER_ITEMS(OrderItemID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (CustomerID) REFERENCES USERS(UserID)
		ON DELETE RESTRICT
        ON UPDATE CASCADE
);
